# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2c8164077d7c553cb6d2625859159b1e9967593f907ba067aaff718548e4bd1861e0f5a6b6656595a5460fc8beac6a3a4f40543068355cebd0810233b185612

test:
  secret_key_base: 0edc7c0015a07464c533966de6f1db0b0e36475ad3e943e435c67fad907cc7058c2407d4059f7a6395841f05b7a451fe4a6c9af0c64d3e17d79bc8cd50bd6425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
